language: R
cache: packages
sudo: false

warnings_are_errors: true

before_install:
  - sudo apt-get install -y gdal
  - R -e "install.packages('rgdal', repos = 'http://cran.rstudio.com')"

bioc_required: true

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  # Try to compile docker image
  # - make docker_build
