language: R
cache: packages
sudo: false

warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev

bioc_required: true

r_packages:
  - covr

before_script:
  - R -e "install.packages('rgdal', repos = 'http://cran.rstudio.com')"


after_success:
  - Rscript -e 'covr::codecov()'
  # Try to compile docker image
  # - make docker_build
