---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, message = FALSE)
```



Load example dataset (sub sample of A. Thaliana dataset)
```{r data}
library(tess3r)
data(data.at)
```


Run of tess3
```{r run, dependson=c("data"), results="hide"}
tess3.obj <- tess3(X = data.at$X, coord = data.at$coord, K = 1:10, ploidy = 1, openMP.core.num = 4)
```

Plot of $RMSE(X, Q * G^T)$ for different value of $K$
```{r rmse.plot, dependson=c("run")}
plot(tess3.obj, ylab = " RMSE(X, Q * t(G))")
```

Plot of $Q$ for $K = 3$
```{r Q.plot, dependson=c("run")}
# retrieve tess3 result for K = 3
tess3.res <- Gettess3res(tess3.obj, K = 3)
# baplot of Q order along longitude
barplot(t(tess3.res$Q[order(data.at$coord[,1]),]), col = 2:4, border = NA)
barplot(tess3.res$Q, border = NA, space = 0)
# Q mapping on coord
plot(tess3.res$Q, data.at$coord, plot.type = "max", interpolation.function = krigging())
```


Plot of $G$ for $K = 3$
```{r G.plot, dependson=c("run")}
# retrieve tess3 result for K = 3
tess3.res <- Gettess3res(tess3.obj, K = 3)
# histogram
hist(tess3.res$pvalue)
cat("gif = ",tess3.res$gif,"\n")
# manhattan plot
plot(tess3.res$pvalue, cex = 0.1)
```

