# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' TODO
#' @export
X2XBin <- function(X, ploidy) {
    .Call('tess3rExperiment_X2XBin', PACKAGE = 'tess3rExperiment', X, ploidy)
}

#' TODO
#' @export
XBin2X <- function(XBin, ploidy) {
    .Call('tess3rExperiment_XBin2X', PACKAGE = 'tess3rExperiment', XBin, ploidy)
}

#' TODO
#'
ComputeHeatKernelWeightSparse <- function(coord, sigma) {
    .Call('tess3rExperiment_ComputeHeatKernelWeightSparse', PACKAGE = 'tess3rExperiment', coord, sigma)
}

#' TODO
#'
#' @export
ComputeHeatKernelWeight <- function(coord, sigma) {
    .Call('tess3rExperiment_ComputeHeatKernelWeight', PACKAGE = 'tess3rExperiment', coord, sigma)
}

#' TODO
#'
ComputeZHelper <- function(Q, n, L) {
    .Call('tess3rExperiment_ComputeZHelper', PACKAGE = 'tess3rExperiment', Q, n, L)
}

#' TODO
#'
ComputeAdmixtedGeno <- function(geno, Z, n, L) {
    .Call('tess3rExperiment_ComputeAdmixtedGeno', PACKAGE = 'tess3rExperiment', geno, Z, n, L)
}

#' TODO
ComputeFst <- function(Q, G, D) {
    .Call('tess3rExperiment_ComputeFst', PACKAGE = 'tess3rExperiment', Q, G, D)
}

InitOpenMP <- function(n) {
    invisible(.Call('tess3rExperiment_InitOpenMP', PACKAGE = 'tess3rExperiment', n))
}

#' solve min || X - Q G^T|| + lambda * tr(Q^T Lapl Q)
ComputeMCPASolution <- function(X, K, Lapl, lambdaPrim, D, maxIteration, tolerance, Q, G) {
    .Call('tess3rExperiment_ComputeMCPASolution', PACKAGE = 'tess3rExperiment', X, K, Lapl, lambdaPrim, D, maxIteration, tolerance, Q, G)
}

