# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' TODO
ComputeXBin <- function(M, d) {
    .Call('TESS3enchoSen_ComputeXBin', PACKAGE = 'TESS3enchoSen', M, d)
}

#' TODO
ComputeXFromXBin <- function(MBin, d) {
    .Call('TESS3enchoSen_ComputeXFromXBin', PACKAGE = 'TESS3enchoSen', MBin, d)
}

#' || X - Q G^T|| + lambda * tr(Q^T Lapl Q)
ComputeMCPASolution <- function(X, K, Lapl, lambdaPrim, D, maxIteration) {
    .Call('TESS3enchoSen_ComputeMCPASolution', PACKAGE = 'TESS3enchoSen', X, K, Lapl, lambdaPrim, D, maxIteration)
}

