# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' TODO
#' @export
ComputeRmse <- function(Q1, Q2) {
    .Call('tess3r_ComputeRmse', PACKAGE = 'tess3r', Q1, Q2)
}

#' TODO
#' @export
ComputeAveragedCrossEntropy <- function(P, Q) {
    .Call('tess3r_ComputeAveragedCrossEntropy', PACKAGE = 'tess3r', P, Q)
}

#' TODO
#' @export
X2XBin <- function(X, ploidy, XBin) {
    invisible(.Call('tess3r_X2XBin', PACKAGE = 'tess3r', X, ploidy, XBin))
}

#' TODO
#' @export
XBin2X <- function(XBin, ploidy) {
    .Call('tess3r_XBin2X', PACKAGE = 'tess3r', XBin, ploidy)
}

#' TODO
#'
ComputeHeatKernelWeightSparse <- function(coord, sigma) {
    .Call('tess3r_ComputeHeatKernelWeightSparse', PACKAGE = 'tess3r', coord, sigma)
}

#' TODO
#'
#' @export
ComputeHeatKernelWeight <- function(coord, sigma) {
    .Call('tess3r_ComputeHeatKernelWeight', PACKAGE = 'tess3r', coord, sigma)
}

#' TODO
#'
#' @export
ComputeExponetialWeight <- function(coord, sigma) {
    .Call('tess3r_ComputeExponetialWeight', PACKAGE = 'tess3r', coord, sigma)
}

#' TODO
#' @export
SampleGenoFromGenerativeModelTESS3 <- function(Q, G, coord, ploidy, openMP_core_num = 1L) {
    .Call('tess3r_SampleGenoFromGenerativeModelTESS3', PACKAGE = 'tess3r', Q, G, coord, ploidy, openMP_core_num)
}

#' TODO
#'
ComputeZHelper <- function(Q, n, L) {
    .Call('tess3r_ComputeZHelper', PACKAGE = 'tess3r', Q, n, L)
}

#' TODO
#'
ComputeAdmixtedGeno <- function(geno, Z, n, L) {
    .Call('tess3r_ComputeAdmixtedGeno', PACKAGE = 'tess3r', geno, Z, n, L)
}

#' TODO
ComputeFst <- function(Q, G, D) {
    .Call('tess3r_ComputeFst', PACKAGE = 'tess3r', Q, G, D)
}

InitOpenMP <- function(n) {
    invisible(.Call('tess3r_InitOpenMP', PACKAGE = 'tess3r', n))
}

#' solve min || X - Q G^T|| + lambda * tr(Q^T Lapl Q)
ComputeMCPASolution <- function(X, K, Lapl, lambdaPrim, D, maxIteration, tolerance, Q, G, verbose) {
    invisible(.Call('tess3r_ComputeMCPASolution', PACKAGE = 'tess3r', X, K, Lapl, lambdaPrim, D, maxIteration, tolerance, Q, G, verbose))
}

#' solve min || X - Q G^T|| + lambda * tr(Q^T Lapl Q)
ComputeMCPASolutionNoCopyX <- function(X, K, Lapl, lambdaPrim, D, maxIteration, tolerance, Q, G, verbose) {
    invisible(.Call('tess3r_ComputeMCPASolutionNoCopyX', PACKAGE = 'tess3r', X, K, Lapl, lambdaPrim, D, maxIteration, tolerance, Q, G, verbose))
}

